### ISSUE TITLE
残っているToDo

### ISSUE THREAD

**Issue by hysdkzm** [hysdkzm/research_hysdkzm#15]
# 学校関係
- [x] サーバー調整
火曜日にLAN変換器が届く
・自分のPCを研究室WIFIに繋げてデザリングで対応できるか
・GPU(Windows)のデザリングで対応できるか
→最悪江口さんのアンドロイドでデザリングでできるか？

- [x] CSSコーディング
・CSSグリッドでteamsのビデオ会議みたいにできるか
~→まずは写真で実験
→グリッド内に写真が納まるように、被らないように~
→webカメラを対象とする　サイズ 640×480
このサイズで分割できるのか

- [x] 研究
・bboxの座標をブラウザ上で出力側に送信
→サーバー側では検出だけしてその座標情報をユーザに送る
→フロント(JS)でbbox描画できるか
> # 今後のToDo
> ## 順番
> ~**1.USBカメラをブラウザ上で認識~
> ~2. aiortc（python）×YOLOの実装~
> 3. コードを解析（ここが一番時間かかる）
> →主にYOLOにどのような形で動画を送っているのか、YOLOに対する実行ｃｏｍｍａｎｄはどこか何か、どのように動画を返すかなど
> 4. nodeのwebrtc版に反映（ここも時間かかる）**
# プロジェクト演習関連
- [x] WSL+ブリンキー環境構築
・SLACKのやり方見ながらもう一度初めからやり直す
- [x] opencvで色検知
今週撮影がなかったとしても、360度動画で色を検知できるか
# 就活関係
- [x] Yahooの日程調整
~→早めに~
## →11/18(水) 17:00~
- [x] SCSKに日程変更できるか
~→一番早めに~
### →→10/28(水)　14:15~
- [ ] いい生活ES

**Comment by hysdkzm** [comment]
# 10/25のToDo
- [x] 掃除

- [x] 何時から出かけるか

**Comment by hysdkzm** [comment]
# Kurento構築の時の参考
https://developer.aliyun.com/article/762221

**Comment by hysdkzm** [comment]
# 10/26 ToDo
~□ WSL+ブリンキー環境構築
・SLACKのやり方見ながらもう一度初めからやり直す
□ opencvで色検知
今週撮影がなかったとしても、360度動画で色を検知できるか~

**Comment by hysdkzm** [comment]
# 10/27 ToDo
□ opencvで色検知
今週撮影がなかったとしても、360度動画で色を検知できるか
**→360度カメラでブリンキーの赤色のLEDが光っている動画を撮影
→opencvで赤色を検出できるか**

参考：https://qiita.com/ueue/items/6bf8fb6bc595e984b0e9
　　　https://qiita.com/hsgucci/items/e9a65d4fa3d279e4219e

**Comment by hysdkzm** [comment]
# 研究プロジェクトについて

> @Sasakata-ikuya @Hayashida-kazuma
> 【短期的な目標】ブリンキーの光った色を全天球カメラで感知、色に応じたイベント検出(最初から色と強弱による多数のイベントの検知は難しいと思うので最初は単純な問題設定から)
> ・TODO(10/29までにできるならやりたい)
> 1.小野研の学生からブリンキーのソースコードを受け取って解読しつつ勉強(笹方)(10/19にミーティング有)
> 2.全天球カメラで光の色と強弱のリアルタイムな検出が可能かどうか、確認、勉強(林田)
> 3.小野研で似たような実験をしている学生からソースコードを受け取る(林田)(10/19にミーティング有)
> 4.時系列データを扱った機械学習の勉強、DCASEが参考になる(長我部)
> 5.ブリンキーと全天球カメラを使って何種類かのイベント(ドアの開閉など)の動画、音声のサンプルデータをとる実験、多めに取ってやりやすいイベントを使う(林田、長我部)

**Comment by hysdkzm** [comment]
# 10/28 ToDo
- [ ] かなとにB4のコードのことを聞く

→クラッシュする

- [x] YOLO_WSの実装(30分かけてできなかったらあきらめ)

- [x] テキストベース(txtかjson)でサーバーからクライアントに送信できるか？

- [x] SCSKインターン

**Comment by hysdkzm** [comment]
0: "b'person', 0.999785840511322, (266.2914123535156, 176.89511108398438, 321.1275939941406, 353.2244567871094)"
1: "b'chair', 0.9536172747612, (93.57262420654297, 284.5643310546875, 75.32862854003906, 107.84553527832031)"

**Comment by hysdkzm** [comment]
# 11/04ToDo

- [x] 研究プロジェクトコーディング
→B4の子にコードの説明を聞きたい
→無理ならスラックでヘルプを求める（小野先生にでも木下先生にでも）
→→B4の子にダイレクトメッセージでもよい

- [x] 研究
 
~→→if文 None　の時も追加
→→わんちゃん　配列じゃなくて文字列説あるから調整
→1フレームの検出結果を1つの2次元配列に
昼めし食うまで：研究の方
昼めし食う前：一回テストしてB4の子にダイレクトメール
昼めし後：研究プロジェクト~
### →→FPSが統一されていない

検出結果が返ってきて描画するまで明らかに時間がかかっている

→シンプルにコーディングの仕方が原因ならばありがたい

**Comment by hysdkzm** [comment]
uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'

**Comment by hysdkzm** [comment]
# 先の研究ToDo

- [ ] 360度カメラを使って実験

→colabのやつで

- [ ] GPUマシンで360度カメラ実験

→うえのやつがダメだった時、もしくは認識精度が悪い時

→一時的に外部通信LANを使って実験

- [ ] 全天球カメラ画像の学習

→　cocodata（4万枚）　+ 撮影した全天球カメラ画像(1万枚)　(+Cube2DMで生成したひしゃげ画像) 


## 金土日で

- [ ] 検出結果を描画したoutputは出さず、入力動画だけのやつに変更(WSLでやった奴)

→index.html , client.js , python.py, css ,transform.pyを編集　(darknet_video.pyは移行だけかも)
→　YOLOとの連携が確認出来たら、rectを追加

- [ ] Yahoo面接対策　コーディング復習

- [ ] 研究プロジェクトのコード眺める

**Comment by htsdkzm2** [comment]
Kurento構築の時の参考(続き)

フロント側にもstunserverなどの設定をしたら成功した。
外部から繋げるかどうかは今後検討
