### ISSUE TITLE
GW以降 ToDo

### ISSUE THREAD

**Issue by hysdkzm** [hysdkzm/research_hysdkzm#26]
- [ ] zozotownの引き落としカード確認

- [ ] Macの初期セットアップ（続き）

**Comment by htsdkzm2** [comment]
![ink (4)](https://user-images.githubusercontent.com/83204189/117643839-cf531600-b1c3-11eb-9895-1be9176c42f2.png)

**Comment by htsdkzm2** [comment]
![ink (5)](https://user-images.githubusercontent.com/83204189/119393135-85157d00-bd0b-11eb-8690-44b5a65e0cf5.png)

**Comment by hysdkzm** [comment]
- [ ] 嶋田ひろき奢られるか奢られるか問題
